print(1 == 1)
print(1 == 2)
print(1 != 2)
print(3 < 5)
print(5 > 3)
print(3 <= 3)
print(4 >= 5)
print(True == 1)
print(True is 1)
print(None is None)
print(not False)
print(not True)
print(1 and 2)
print(0 or 5)
print(True and False)
print(False or True)
print(1 in [1, 2])
print(3 in [1, 2])
print("a" in "cat")
print("z" in "cat")
print(1 < 5 < 9)
print(isinstance(1, int))
print(any([0, 1]))
print(all([1, 1]))
print(all([1, 0]))
print(any([]))
print(all([]))
