#!/bin/sh
# One-liner: /home/bob/Ailang-Self-Hosting-/CAD/display3d/vk-test
cd /home/bob/Ailang-Self-Hosting-/CAD/display3d || exit 1
export LD_LIBRARY_PATH=.
export AILANG_VK_DEVICE="${AILANG_VK_DEVICE:-gpu}"
exec make test
