#!/usr/bin/env python3
"""Scaffold an AILang board profile (ailang.board/v1) for humans or models.

Examples:
  python3 tools/board_profile_scaffold.py --name my_board --vendor gowin --part GW1NR-LV9QN88PC6/I5
  python3 tools/board_profile_scaffold.py --name icebreaker --vendor lattice --part iCE40UP5K-SG48
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold ailang.board/v1 JSON")
    ap.add_argument("--name", required=True, help="board id, e.g. tang_nano_9k")
    ap.add_argument("--vendor", default="other", help="gowin|lattice|xilinx|intel|sim|other")
    ap.add_argument("--part", default="UNKNOWN", help="device part string")
    ap.add_argument("--family", default="", help="device family")
    ap.add_argument("--display", default="", help="human display name")
    ap.add_argument("--loader-board", default="", help="openFPGALoader -b name")
    ap.add_argument("--clk-hz", type=int, default=27_000_000)
    ap.add_argument("--clk-pin", default="CLK")
    ap.add_argument("--root", type=Path, default=Path("boards"))
    ap.add_argument("--catalog", action="store_true", help="append to catalog.json")
    args = ap.parse_args()

    name = args.name.strip().replace(" ", "_")
    board_dir = args.root / name
    board_dir.mkdir(parents=True, exist_ok=True)

    profile = {
        "schema": "ailang.board/v1",
        "name": name,
        "display_name": args.display or name.replace("_", " ").title(),
        "vendor": args.vendor,
        "device": {
            "part": args.part,
            "family": args.family or args.vendor,
            "loader_board": args.loader_board or name.replace("_", ""),
            "synth": {
                "gowin": "gowin",
                "lattice": "ice40",
                "xilinx": "xilinx",
                "sim": "none",
            }.get(args.vendor, "none"),
        },
        "clocks": {
            "clk": {
                "hz": args.clk_hz,
                "pin": str(args.clk_pin),
                "iostandard": "LVCMOS33",
            }
        },
        "resources": {
            "led": {
                "dir": "out",
                "width": 1,
                "pins": ["LED0"],
                "iostandard": "LVCMOS33",
                "invert": False,
                "notes": "TODO: fill from schematic",
            }
        },
        "defaults": {"clk": "clk", "rst": {"tie": 0}},
        "meta": {
            "author": "scaffold",
            "license": "CC0-1.0",
            "notes": "Generated by tools/board_profile_scaffold.py — edit pins!",
        },
    }

    board_path = board_dir / "board.json"
    board_path.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {board_path}")

    bind = {
        "schema": "ailang.board.bind/v1",
        "board": name,
        "bind": {"clk": "clk", "rst": None},
        "policy": {"unbound_out": "warn", "unbound_in": "warn", "emit_wrapper": True},
    }
    bind_path = board_dir / "bind_example.json"
    bind_path.write_text(json.dumps(bind, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {bind_path}")

    if args.catalog:
        cat_path = args.root / "catalog.json"
        if cat_path.exists():
            cat = json.loads(cat_path.read_text(encoding="utf-8"))
        else:
            cat = {"schema": "ailang.board.catalog/v1", "boards": []}
        entry = {
            "name": name,
            "display_name": profile["display_name"],
            "path": f"{name}/board.json",
            "vendor": args.vendor,
            "part": args.part,
            "tags": [args.vendor],
        }
        names = {b.get("name") for b in cat.get("boards", [])}
        if name not in names:
            cat.setdefault("boards", []).append(entry)
            cat_path.write_text(json.dumps(cat, indent=2) + "\n", encoding="utf-8")
            print(f"updated {cat_path}")
        else:
            print(f"catalog already has {name}")

    print("Next: fill resources.pins from the board schematic, then:")
    print(f"  ./ailang_hdl.x -hdl -board {board_path} your.ailang out/x")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
